# Generated by Django 3.2.4 on 2021-06-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_nac', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
